name: Deploy documentation

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/docs.yml
    - docs/**

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.0-beta.4 - 3.9.0

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt install plantuml
        python -m pip install -r docs/requirements.txt

    - name: Build site
      working-directory: docs
      run: make html

    - name: Configure git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.email mcsinyx@disroot.org
        git config user.name Nguyễn\ Gia\ Phong
        git remote set-url origin \
          https://token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        git fetch origin gh-pages

    - name: Deploy site
      run: |
        git switch gh-pages
        git rm -r .
        shopt -s dotglob
        mv docs/build/html/* .

        rm -r docs
        git add .
        if git commit -m "Build at $(date --iso-8601=seconds)"
        then
          git push origin gh-pages
        fi
